@startuml TP3_CPP
PlayStrategy <-- connectFourStrategy
PlayStrategy <-- ticTacToeStrategy

Game o--> PlayStrategy
Game "1" o-- "1" Grid : Contain
Player "2" o-- "1..n" Game : Play

class Game {
+ placeToken()
+ checkVictory()
}

class Player {
+name : string
+symbol : string
}

class Grid {
- grid : array
+ placeElement(x, y, element) : void
}

interface PlayStrategy {
placeToken()
checkVictory()
}

@enduml